-- Add deduction_mode column to emp_loan table
-- Tracks whether deductions are automatic or manual
-- Values: 'automatic' (auto-generated by system) or 'manual' (user added each month)

ALTER TABLE `emp_loan` 
ADD COLUMN `deduction_mode` ENUM('automatic', 'manual') DEFAULT 'automatic' 
AFTER `monthly_deduction`;

-- Add index for filtering
CREATE INDEX `idx_deduction_mode` ON `emp_loan`(`deduction_mode`);

-- Update existing loans to 'automatic' (legacy default behavior)
UPDATE `emp_loan` 
SET `deduction_mode` = 'automatic' 
WHERE `deduction_mode` IS NULL;
