CREATE TABLE IF NOT EXISTS `emp_vacation_activity_log` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `emp_id` VARCHAR(20) NOT NULL,
    `vac_id` INT NOT NULL DEFAULT 0,
    `action_type` VARCHAR(50) NOT NULL,
    `old_available_balance` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `old_used_days` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `old_remaining_balance` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `new_available_balance` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `new_used_days` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `new_remaining_balance` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `change_amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `carryover_days` DECIMAL(10,2) DEFAULT 0.00,
    `total_days` DECIMAL(10,2) DEFAULT NULL,
    `period_start` DATE DEFAULT NULL,
    `period_end` DATE DEFAULT NULL,
    `performed_by_emp_id` VARCHAR(20) DEFAULT NULL,
    `notes` TEXT DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_emp_id` (`emp_id`),
    KEY `idx_vac_id` (`vac_id`),
    KEY `idx_action_type` (`action_type`),
    KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
